/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplatesImport } from './routes/templates'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as EditorTemplateIdImport } from './routes/editor.$templateId'

// Create/Update Routes

const TemplatesRoute = TemplatesImport.update({
  path: '/templates',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditorTemplateIdRoute = EditorTemplateIdImport.update({
  path: '/editor/$templateId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesImport
      parentRoute: typeof rootRoute
    }
    '/editor/$templateId': {
      id: '/editor/$templateId'
      path: '/editor/$templateId'
      fullPath: '/editor/$templateId'
      preLoaderRoute: typeof EditorTemplateIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/editor/$templateId': typeof EditorTemplateIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/editor/$templateId': typeof EditorTemplateIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/templates': typeof TemplatesRoute
  '/editor/$templateId': typeof EditorTemplateIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/templates' | '/editor/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/templates' | '/editor/$templateId'
  id: '__root__' | '/' | '/about' | '/templates' | '/editor/$templateId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TemplatesRoute: typeof TemplatesRoute
  EditorTemplateIdRoute: typeof EditorTemplateIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TemplatesRoute: TemplatesRoute,
  EditorTemplateIdRoute: EditorTemplateIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/templates",
        "/editor/$templateId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/templates": {
      "filePath": "templates.tsx"
    },
    "/editor/$templateId": {
      "filePath": "editor.$templateId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
